- hosts: localhost
  connection: local
  tags: always
  pre_tasks:
    - name: pre-run | update package cache (fedora)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Fedora"
      
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
      
    - name: pre-run | install homebrew if not installed (homebrew) 
      tags: always
      shell: command -v brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      changed_when: False
      when: ansible_distribution == "MacOSX"
        

    - name: pre-run | update package cache (macos)
      tags: always
      homebrew: update_homebrew=yes
      changed_when: False
      when: ansible_distribution == "MacOSX"
        
- hosts: localhost
  connection: local
  tasks:
  - name: Install packages
    ignore_errors: yes
    become: yes
    package: 
      state:  latest
      name:
        - python
        - bash
        - bash-completion
        - bat
        - cargo
        - coreutils
        - curl
        - dos2unix
        - fd
        - findutils
        - fish
        - fzf
        - gawk
        - gh
        - git
        - jq
        - lsd
        - neofetch
        - neovim
        - nmap
        - rbenv
        - rust
        - rustup-init
        - stow
        - telnet
        - tldr
        - tmux
        - vim
        - wget
        - zoxide
        - zsh
        - zsh-vi-mode

  - name: Install zsh-vi-mode
    git:
      repo: https://github.com/jeffreytse/zsh-vi-mode.git
      dest: $HOME/.opt
      when: ansible_distribution == "Fedora"
        
  - name: Clone my dotfiles
    git:
      repo: git@github.com:sammagnum/.dotfiles.git
      dest: $HOME/.dotfiles
      
  - name: stow my dotfiles
    stow:
      state: latest
      package: '{{ item }}'
      dir: $HOME/.dotfiles
    with_items:
    - nvim
    - starship
    - tmux
    - vim
    - zsh
